from __future__ import annotations

from pathlib import Path

import jsonschema
import yaml
from dcc_mcp_core.skill import skill_success

import dcc_mcp_obs


def main() -> None:
    package_root = Path(dcc_mcp_obs.__file__).resolve().parent
    skill_root = package_root / "skills" / "obs-control"
    skill_text = (skill_root / "SKILL.md").read_text(encoding="utf-8")
    tools = yaml.safe_load((skill_root / "tools.yaml").read_text(encoding="utf-8"))["tools"]
    identity = {
        "instanceId": "obs-wheel-contract",
        "pluginVersion": dcc_mcp_obs.__version__,
        "obsVersion": "31.1.1",
        "hostPid": 4242,
        "eventSequence": 7,
        "ok": True,
    }
    results = {
        "get_status": {**identity, "ready": True},
        "request_graceful_shutdown": {
            **identity,
            "accepted": True,
            "shutdownScheduled": True,
        },
        "list_scenes": {
            **identity,
            "currentSceneName": "Main",
            "scenes": [{"sceneName": "Main"}],
            "truncated": False,
        },
        "capture_program_frame": {
            **identity,
            "sourceName": "Main",
            "imageFormat": "png",
            "imageData": "data:image/png;base64," + ("A" * 64),
            "imageWidth": 320,
            "imageHeight": 180,
            "byteLength": 48,
            "sha256": "0" * 64,
        },
        "list_sources": {
            **identity,
            "sceneName": "Main",
            "sources": [
                {
                    "sceneItemId": 1,
                    "sourceName": "Camera",
                    "sourceKind": "video_capture_device",
                    "enabled": True,
                }
            ],
            "truncated": False,
        },
        "get_recording_status": {
            **identity,
            "outputActive": False,
            "outputPaused": False,
        },
        "start_recording": {
            **identity,
            "outputActive": True,
            "outputPaused": False,
            "verified": True,
        },
        "stop_recording": {
            **identity,
            "outputActive": False,
            "outputPaused": False,
            "verified": True,
        },
        "pause_recording": {
            **identity,
            "outputActive": True,
            "outputPaused": True,
            "verified": True,
        },
        "resume_recording": {
            **identity,
            "outputActive": True,
            "outputPaused": False,
            "verified": True,
        },
        "get_scene_recording_session": {
            **identity,
            "sessionId": "01234567-89ab-cdef-0123-456789abcdef",
            "sessionActive": True,
            "startedAt": "2026-09-01T08:00:00+08:00",
            "recordings": [
                {
                    "sceneName": "RL - Game 1",
                    "fileName": "Game 1 2026-09-01 08-00-00.mp4",
                    "outputPath": "/recordings/Game 1 2026-09-01 08-00-00.mp4",
                    "outputActive": True,
                    "videoOnly": True,
                    "videoWidth": 1920,
                    "videoHeight": 1080,
                    "totalBytes": 4096,
                    "totalFrames": 30,
                    "lastError": "",
                }
            ],
        },
        "start_scene_recordings": {
            **identity,
            "sessionId": "01234567-89ab-cdef-0123-456789abcdef",
            "sessionActive": True,
            "startedAt": "2026-09-01T08:00:00+08:00",
            "recordings": [
                {
                    "sceneName": "RL - Game 1",
                    "fileName": "Game 1 2026-09-01 08-00-00.mp4",
                    "outputPath": "/recordings/Game 1 2026-09-01 08-00-00.mp4",
                    "outputActive": True,
                    "videoOnly": True,
                    "videoWidth": 1920,
                    "videoHeight": 1080,
                    "totalBytes": 0,
                    "totalFrames": 0,
                    "lastError": "",
                }
            ],
            "verified": True,
        },
        "stop_scene_recordings": {
            **identity,
            "sessionId": "01234567-89ab-cdef-0123-456789abcdef",
            "sessionActive": False,
            "startedAt": "2026-09-01T08:00:00+08:00",
            "recordings": [
                {
                    "sceneName": "RL - Game 1",
                    "fileName": "Game 1 2026-09-01 08-00-00.mp4",
                    "outputPath": "/recordings/Game 1 2026-09-01 08-00-00.mp4",
                    "outputActive": False,
                    "videoOnly": True,
                    "videoWidth": 1920,
                    "videoHeight": 1080,
                    "totalBytes": 8192,
                    "totalFrames": 60,
                    "lastError": "",
                }
            ],
            "verified": True,
        },
        "get_streaming_status": {**identity, "streamingActive": False},
        "start_streaming": {**identity, "streamingActive": True, "verified": True},
        "stop_streaming": {**identity, "streamingActive": False, "verified": True},
        "get_replay_buffer_status": {**identity, "replayBufferActive": False},
        "start_replay_buffer": {**identity, "replayBufferActive": True, "verified": True},
        "stop_replay_buffer": {**identity, "replayBufferActive": False, "verified": True},
        "save_replay_buffer": {
            **identity,
            "replayBufferActive": True,
            "accepted": True,
            "submitted": True,
        },
        "get_virtual_camera_status": {**identity, "virtualCameraActive": False},
        "start_virtual_camera": {**identity, "virtualCameraActive": True, "verified": True},
        "stop_virtual_camera": {**identity, "virtualCameraActive": False, "verified": True},
        "list_outputs": {
            **identity,
            "outputs": [
                {"outputName": "streaming", "outputKind": "streaming", "outputActive": False}
            ],
            "truncated": False,
        },
        "get_output_status": {
            **identity,
            "outputName": "streaming",
            "outputKind": "streaming",
            "outputActive": False,
        },
        "start_output": {
            **identity,
            "outputName": "streaming",
            "outputKind": "streaming",
            "outputActive": True,
            "verified": True,
        },
        "stop_output": {
            **identity,
            "outputName": "streaming",
            "outputKind": "streaming",
            "outputActive": False,
            "verified": True,
        },
        "list_profiles": {**identity, "profiles": [{"profileName": "Main"}], "truncated": False},
        "get_current_profile": {**identity, "profileName": "Main"},
        "set_current_profile": {**identity, "profileName": "Main", "verified": True},
        "list_scene_collections": {
            **identity,
            "sceneCollections": [{"sceneCollectionName": "Main"}],
            "truncated": False,
        },
        "get_current_scene_collection": {**identity, "sceneCollectionName": "Main"},
        "set_current_scene_collection": {
            **identity,
            "sceneCollectionName": "Main",
            "verified": True,
        },
        "list_allowlisted_hotkeys": {
            **identity,
            "hotkeys": [{"hotkeyName": "start_streaming"}],
            "truncated": False,
        },
        "trigger_allowlisted_hotkey": {
            **identity,
            "hotkeyName": "start_streaming",
            "accepted": True,
        },
        "get_operator_status": {
            **identity,
            "ready": True,
            "uiThreadReady": True,
            "configPathRedacted": True,
            "profileName": "Main",
            "sceneCollectionName": "Main",
        },
        "get_current_scene": {**identity, "sceneName": "Main"},
        "set_current_scene": {**identity, "sceneName": "Main", "verified": True},
        "list_scene_items": {**identity, "sceneName": "Main", "sceneItems": [], "truncated": False},
        "create_scene_item": {
            **identity,
            "sceneName": "Main",
            "sceneItemId": 1,
            "sourceName": "Camera",
            "sourceKind": "mock",
            "enabled": True,
            "verified": True,
        },
        "get_window_capture_source": {
            **identity,
            "sceneName": "RL - Bazaar",
            "sceneItemId": 7,
            "sourceName": "RL - Bazaar Window",
            "sourceKind": "window_capture",
            "enabled": True,
            "processId": 30520,
            "windowHandle": 147140366,
            "windowTitle": "The Bazaar",
            "windowClass": "UnrealWindow",
            "executable": "Bazaar.exe",
            "captureCursor": False,
            "clientArea": True,
            "captureMethod": "automatic",
            "bindingVerified": True,
            "verified": True,
        },
        "list_window_capture_candidates": {
            **identity,
            "executable": "b1-Win64-Shipping.exe",
            "windowTitle": "b1  ",
            "candidates": [
                {
                    "processId": 120000,
                    "windowHandle": 220000000,
                    "windowTitle": "b1  ",
                    "windowClass": "UnrealWindow",
                    "executable": "b1-Win64-Shipping.exe",
                    "visible": True,
                    "minimized": False,
                    "clientWidth": 1066,
                    "clientHeight": 600,
                    "captureReady": True,
                }
            ],
            "truncated": False,
        },
        "restore_window_capture_candidate": {
            **identity,
            "processId": 120000,
            "windowHandle": 220000000,
            "windowTitle": "b1  ",
            "windowClass": "UnrealWindow",
            "executable": "b1-Win64-Shipping.exe",
            "visible": True,
            "minimized": False,
            "clientWidth": 1066,
            "clientHeight": 600,
            "captureReady": True,
            "verified": True,
        },
        "create_window_capture_source": {
            **identity,
            "sceneName": "RL - Bazaar",
            "sceneItemId": 7,
            "sourceName": "RL - Bazaar Window",
            "sourceKind": "window_capture",
            "enabled": True,
            "processId": 30520,
            "windowHandle": 147140366,
            "windowTitle": "The Bazaar",
            "windowClass": "UnrealWindow",
            "executable": "Bazaar.exe",
            "captureCursor": False,
            "clientArea": True,
            "captureMethod": "automatic",
            "bindingVerified": True,
            "verified": True,
        },
        "rebind_window_capture_source": {
            **identity,
            "sceneName": "RL - Wukong",
            "sceneItemId": 7,
            "sourceName": "RL - Wukong Window",
            "sourceKind": "window_capture",
            "enabled": True,
            "processId": 120000,
            "windowHandle": 220000000,
            "windowTitle": "b1  ",
            "windowClass": "UnrealWindow",
            "executable": "b1-Win64-Shipping.exe",
            "captureCursor": False,
            "clientArea": True,
            "captureMethod": "windows_graphics_capture",
            "bindingVerified": True,
            "verified": True,
        },
        "set_window_capture_method": {
            **identity,
            "sceneName": "RL - Bazaar",
            "sceneItemId": 7,
            "sourceName": "RL - Bazaar Window",
            "sourceKind": "window_capture",
            "enabled": True,
            "processId": 30520,
            "windowHandle": 147140366,
            "windowTitle": "The Bazaar",
            "windowClass": "UnrealWindow",
            "executable": "Bazaar.exe",
            "captureCursor": False,
            "clientArea": True,
            "captureMethod": "windows_graphics_capture",
            "bindingVerified": True,
            "verified": True,
        },
        "set_scene_item_enabled": {
            **identity,
            "sceneName": "Main",
            "sceneItemId": 1,
            "sourceName": "Camera",
            "sourceKind": "mock",
            "enabled": False,
            "verified": True,
        },
        "remove_scene_item": {
            **identity,
            "sceneName": "Main",
            "sceneItemId": 1,
            "removed": True,
            "verified": True,
        },
        "list_transitions": {**identity, "transitions": [], "truncated": False},
        "set_current_transition": {**identity, "transitionName": "Fade", "verified": True},
        "trigger_transition": {
            **identity,
            "transitionName": "Fade",
            "sceneName": "Main",
            "verified": True,
        },
        "get_studio_mode": {
            **identity,
            "studioModeEnabled": False,
            "previewSceneName": "Main",
            "programSceneName": "Main",
        },
        "set_studio_mode": {**identity, "studioModeEnabled": True, "verified": True},
        "set_preview_scene": {**identity, "sceneName": "Main", "verified": True},
        "transition_to_program": {
            **identity,
            "studioModeEnabled": True,
            "previewSceneName": "Main",
            "programSceneName": "Main",
            "verified": True,
        },
        "create_scene": {**identity, "sceneName": "New", "verified": True},
        "rename_scene": {**identity, "sceneName": "New2", "verified": True},
        "remove_scene": {**identity, "sceneName": "Old", "removed": True, "verified": True},
        "set_scene_item_transform": {
            **identity,
            "sceneName": "Main",
            "sceneItemId": 1,
            "sourceName": "Camera",
            "sourceKind": "mock",
            "enabled": True,
            "verified": True,
        },
        "get_agent_input_overlay": {
            **identity,
            "sceneName": "RL - Game 1",
            "sceneItemId": 8,
            "sourceName": "DCC-MCP Agent Input",
            "sourceKind": "dcc_mcp_agent_input_overlay",
            "theme": "dcc_mcp_dark",
            "anchor": "bottom_right",
            "opacity": 78,
            "margin": 48,
            "agentId": "agent",
            "active": False,
            "activitySequence": 0,
            "eventKind": "none",
            "keys": [],
            "mouseButton": "none",
            "wheelDirection": "none",
            "characterCount": 0,
            "cueLabel": "",
            "durationMs": 0,
            "remainingMs": 0,
        },
        "create_agent_input_overlay": {
            **identity,
            "sceneName": "RL - Game 1",
            "sceneItemId": 8,
            "sourceName": "DCC-MCP Agent Input",
            "sourceKind": "dcc_mcp_agent_input_overlay",
            "theme": "dcc_mcp_dark",
            "anchor": "bottom_right",
            "opacity": 78,
            "margin": 48,
            "agentId": "agent",
            "active": False,
            "activitySequence": 0,
            "eventKind": "none",
            "keys": [],
            "mouseButton": "none",
            "wheelDirection": "none",
            "characterCount": 0,
            "cueLabel": "",
            "durationMs": 0,
            "remainingMs": 0,
            "verified": True,
        },
        "set_agent_input_overlay_layout": {
            **identity,
            "sceneName": "RL - Game 1",
            "sceneItemId": 8,
            "sourceName": "DCC-MCP Agent Input",
            "sourceKind": "dcc_mcp_agent_input_overlay",
            "theme": "dcc_mcp_dark",
            "anchor": "top_left",
            "opacity": 55,
            "margin": 32,
            "agentId": "agent",
            "active": False,
            "activitySequence": 0,
            "eventKind": "none",
            "keys": [],
            "mouseButton": "none",
            "wheelDirection": "none",
            "characterCount": 0,
            "cueLabel": "",
            "durationMs": 0,
            "remainingMs": 0,
            "verified": True,
        },
        "emit_agent_input_activity": {
            **identity,
            "sceneName": "RL - Game 1",
            "sceneItemId": 8,
            "sourceName": "DCC-MCP Agent Input",
            "sourceKind": "dcc_mcp_agent_input_overlay",
            "theme": "dcc_mcp_dark",
            "anchor": "bottom_right",
            "opacity": 78,
            "margin": 48,
            "agentId": "trainer-1",
            "active": True,
            "activitySequence": 1,
            "eventKind": "shortcut",
            "keys": ["ctrl", "shift", "r"],
            "mouseButton": "none",
            "wheelDirection": "none",
            "characterCount": 0,
            "cueLabel": "CTRL + SHIFT + R",
            "durationMs": 1600,
            "remainingMs": 1500,
            "verified": True,
        },
        "clear_agent_input_overlay": {
            **identity,
            "sceneName": "RL - Game 1",
            "sceneItemId": 8,
            "sourceName": "DCC-MCP Agent Input",
            "sourceKind": "dcc_mcp_agent_input_overlay",
            "theme": "dcc_mcp_dark",
            "anchor": "bottom_right",
            "opacity": 78,
            "margin": 48,
            "agentId": "agent",
            "active": False,
            "activitySequence": 2,
            "eventKind": "none",
            "keys": [],
            "mouseButton": "none",
            "wheelDirection": "none",
            "characterCount": 0,
            "cueLabel": "",
            "durationMs": 0,
            "remainingMs": 0,
            "verified": True,
        },
        "get_source_identity": {
            **identity,
            "sourceName": "DCC Safe Color",
            "sourceKind": "color_source_v3",
            "sourceType": "input",
            "outputFlags": 3,
            "active": True,
            "showing": True,
            "width": 1280,
            "height": 720,
        },
        "create_source": {
            **identity,
            "sourceName": "DCC Safe Color",
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "settings": {"width": 1280, "height": 720, "color": 4_278_190_080},
            "verified": True,
        },
        "rename_source": {
            **identity,
            "sourceName": "DCC Safe Color 2",
            "sourceKind": "color_source_v3",
            "sourceType": "input",
            "outputFlags": 3,
            "active": True,
            "showing": True,
            "width": 1280,
            "height": 720,
            "verified": True,
        },
        "remove_source": {**identity, "accepted": True, "removed": True, "verified": True},
        "list_input_kinds": {
            **identity,
            "schemaVersion": "1.0",
            "inputKinds": [{"sourceKind": "color_source_v3", "displayName": "Color Source"}],
        },
        "get_input_settings": {
            **identity,
            "sourceName": "DCC Safe Color",
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "settings": {"width": 1280, "height": 720, "color": 4_278_190_080},
        },
        "set_input_settings": {
            **identity,
            "sourceName": "DCC Safe Color",
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "settings": {"width": 1920, "height": 1080, "color": 4_278_190_080},
            "verified": True,
        },
        "describe_properties": {
            **identity,
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "properties": [
                {"propertyName": "width", "valueType": "integer", "minimum": 1, "maximum": 8192},
                {"propertyName": "height", "valueType": "integer", "minimum": 1, "maximum": 8192},
                {
                    "propertyName": "color",
                    "valueType": "integer",
                    "minimum": 0,
                    "maximum": 4_294_967_295,
                },
            ],
        },
        "validate_property_value": {
            **identity,
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "propertyName": "width",
            "value": 1920,
            "valid": True,
        },
        "set_property_value": {
            **identity,
            "sourceName": "DCC Safe Color",
            "sourceKind": "color_source_v3",
            "schemaVersion": "1.0",
            "settings": {"width": 1920, "height": 720, "color": 4_278_190_080},
            "verified": True,
        },
        "list_filters": {
            **identity,
            "sourceName": "Game Audio",
            "filters": [{"filterName": "Agent Gain", "filterKind": "gain_filter", "enabled": True}],
            "truncated": False,
        },
        "get_filter": {
            **identity,
            "sourceName": "Game Audio",
            "filterName": "Agent Gain",
            "filterKind": "gain_filter",
            "enabled": True,
            "schemaVersion": "1.0",
            "settings": {"db": -3.0},
        },
        "create_filter": {
            **identity,
            "sourceName": "Game Audio",
            "filterName": "Agent Gain",
            "filterKind": "gain_filter",
            "enabled": True,
            "schemaVersion": "1.0",
            "settings": {"db": -3.0},
            "verified": True,
        },
        "set_filter_enabled": {
            **identity,
            "sourceName": "Game Audio",
            "filterName": "Agent Gain",
            "filterKind": "gain_filter",
            "enabled": False,
            "schemaVersion": "1.0",
            "settings": {"db": -3.0},
            "verified": True,
        },
        "set_filter_settings": {
            **identity,
            "sourceName": "Game Audio",
            "filterName": "Agent Gain",
            "filterKind": "gain_filter",
            "enabled": True,
            "schemaVersion": "1.0",
            "settings": {"db": -6.0},
            "verified": True,
        },
        "remove_filter": {**identity, "accepted": True, "removed": True, "verified": True},
        "get_source_volume": {**identity, "sourceName": "Game Audio", "volume": 0.5},
        "set_source_volume": {
            **identity,
            "sourceName": "Game Audio",
            "volume": 0.5,
            "verified": True,
        },
        "get_source_mute": {**identity, "sourceName": "Game Audio", "muted": False},
        "set_source_mute": {
            **identity,
            "sourceName": "Game Audio",
            "muted": True,
            "verified": True,
        },
        "get_source_monitor_type": {
            **identity,
            "sourceName": "Game Audio",
            "monitorType": "none",
        },
        "set_source_monitor_type": {
            **identity,
            "sourceName": "Game Audio",
            "monitorType": "monitor_and_output",
            "verified": True,
        },
        "get_media_status": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "paused",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 2_000,
        },
        "play_media": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "playing",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 2_000,
            "verified": True,
        },
        "pause_media": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "paused",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 2_000,
            "verified": True,
        },
        "restart_media": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "playing",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 0,
            "verified": True,
        },
        "stop_media": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "stopped",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 0,
            "verified": True,
        },
        "seek_media": {
            **identity,
            "sourceName": "Training Replay",
            "mediaState": "paused",
            "mediaDurationMs": 120_000,
            "mediaCursorMs": 2_000,
            "verified": True,
        },
    }

    assert [tool["name"] for tool in tools] == list(results)
    assert "`postcondition.verified=true`" in skill_text
    for tool in tools:
        envelope = skill_success("OBS action completed.", **results[tool["name"]])
        if tool["name"] == "trigger_allowlisted_hotkey":
            assert "postcondition" not in envelope
        jsonschema.Draft202012Validator(tool["output_schema"]).validate(envelope)


if __name__ == "__main__":
    main()
